import DS from 'ember-data';

export default DS.Model.extend({
  "APPLICATION_ID": DS.attr('number'),
  "ACTIVITY": DS.attr('string'),
  "ADMINISTERING_IC": DS.attr('string'),
  "APPLICATION_TYPE": DS.attr('number'),
  "ARRA_FUNDED": DS.attr('string'),
  "AWARD_NOTICE_DATE": DS.attr('string'),
  "BUDGET_START": DS.attr('string'),
  "BUDGET_END": DS.attr('string'),
  "CFDA_CODE": DS.attr('number'),
  "CORE_PROJECT_NUM": DS.attr('string'),
  "ED_INST_TYPE": DS.attr('string'),
  "FOA_NUMBER": DS.attr('string'),
  "FULL_PROJECT_NUM": DS.attr('string'),
  "FUNDING_ICs": DS.attr('string'),
  "FUNDING_MECHANISM": DS.attr('string'),
  "FY": DS.attr('number'),
  "IC_NAME": DS.attr('string'),
  "NIH_SPENDING_CATS": DS.attr('string'),
  "ORG_CITY": DS.attr('string'),
  "ORG_COUNTRY": DS.attr('string'),
  "ORG_DEPT": DS.attr('string'),
  "ORG_DISTRICT": DS.attr('number'),
  "ORG_DUNS": DS.attr('number'),
  "ORG_FIPS": DS.attr('string'),
  "ORG_NAME": DS.attr('string'),
  "ORG_STATE": DS.attr('string'),
  "ORG_ZIPCODE": DS.attr('number'),
  // two features have too much data associated casuing lagged loading
  //"PHR": DS.attr('string'),
  //"PROJECT_TERMS": DS.attr('string'),
  "PI_IDS": DS.attr('string'),
  "PI_NAMEs": DS.attr('string'),
  "PROGRAM_OFFICER_NAME": DS.attr('string'),
  "PROJECT_START": DS.attr('string'),
  "PROJECT_END": DS.attr('string'),
  "PROJECT_TITLE": DS.attr('string'),
  "SERIAL_NUMBER": DS.attr('number'),
  "STUDY_SECTION": DS.attr('string'),
  "STUDY_SECTION_NAME": DS.attr('string'),
  "SUBPROJECT_ID": DS.attr('string'),
  "SUFFIX": DS.attr('string'),
  "SUPPORT_YEAR": DS.attr('number'),
  "DIRECT_COST_AMT": DS.attr('number'),
  "INDIRECT_COST_AMT": DS.attr('number'),
  "TOTAL_COST": DS.attr('number'),
  "TOTAL_COST_SUB_PROJECT": DS.attr('number')
});